# .github/workflows/dispatch-build.yml
name: Build & Push New Golang Docker Build Server Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch or PR ref to build'
        required: true
      tag:
        description: 'Docker image tag (e.g. v1.2.3 or latest)'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU (optional, for multi-arch)
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069

      - name: Login to DockerHub (development repo)
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}

      - name: Build & push development image
        run: |
          docker buildx build \
            --tag mattermostdevelopment/mattermost-build-server:${{ github.event.inputs.tag }} \
            --push \
            -f Dockerfile.buildenv .

      - name: Login to DockerHub (production repo)
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push production image
        run: |
          docker buildx build \
            --tag mattermost/mattermost-build-server:${{ github.event.inputs.tag }} \
            --push \
            -f Dockerfile.buildenv .
